version: "3.8"
services:
  mss:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: mss-server:dev
    ports:
      - "8080:8080"
    environment:
      - MSS_LISTEN_ADDR=:8080
      - MSS_DB_PATH=/data/mss.db
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
